<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sanjeet3149591" ignored="0" name="Order Flow Test" tests="3" failures="1" timestamp="18 Dec 2018 12:39:44 GMT" time="0.418" errors="0">
  <testcase name="placeNewOrderWithAllSameStop" time="0.23" classname="com.nagarro.testCases.TestCasesForPlaceOrderWithAllSameStop">
    <failure type="java.lang.AssertionError" message="expected [0] but found [20.00]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [20.00]
at com.nagarro.testCases.TestCasesForPlaceOrderWithAllSameStop.placeNewOrderWithAllSameStop(TestCasesForPlaceOrderWithAllSameStop.java:81)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- placeNewOrderWithAllSameStop -->
  <testcase name="placeNewOrderInPast" time="0.091" classname="com.nagarro.testCases.TestCasesForPlaceOrderWithInvalideScenaio"/>
  <testcase name="placeNewOrderWithWronJson" time="0.083" classname="com.nagarro.testCases.TestCasesForPlaceOrderWithInvalideScenaio"/>
</testsuite> <!-- Order Flow Test -->
