<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sanjeet3149591" ignored="0" name="Order Flow Test" tests="3" failures="1" timestamp="17 Dec 2018 12:58:35 GMT" time="0.4" errors="0">
  <testcase name="placeNewOrderWithAllSameStop" time="0.207" classname="com.nagarro.testCases.PlaceOrderWithAllSameStopTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [20.00]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [20.00]
at com.nagarro.testCases.PlaceOrderWithAllSameStopTest.placeNewOrderWithAllSameStop(PlaceOrderWithAllSameStopTest.java:80)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- placeNewOrderWithAllSameStop -->
  <testcase name="placeNewOrderInPast" time="0.091" classname="com.nagarro.testCases.PlaceOrderInPastorWithWrongJsonTest"/>
  <testcase name="placeNewOrderWithWronJson" time="0.084" classname="com.nagarro.testCases.PlaceOrderInPastorWithWrongJsonTest"/>
</testsuite> <!-- Order Flow Test -->
