<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sanjeet3149591" ignored="0" name="place order at 3 stops in present and future" tests="16" failures="1" timestamp="20 Dec 2018 16:55:53 GMT" time="68.796" errors="0">
  <testcase name="testcase_Verify_PlaceNewOrder" time="5.286" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__CancelOrder" time="1.576" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__FetchTheOrderDetails" time="1.835" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__TakeTheOrderDetails" time="1.553" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__CompleteTheOrderDetails" time="3.866" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__TakeTheOngoingOrder" time="4.932" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__TakeTheCompletedOrder" time="3.958" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__TakeTheCancelledOrder" time="9.946" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__CompleteTheNewOrder" time="2.125" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__CompleteTheOrderAfterCompleted" time="4.785" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__CancelTheOrderAfterCompleted" time="3.298" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__TakeTheOrderAfterCompleted" time="8.684" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__CancelTheOrderAfterCancel" time="3.721" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture">
    <failure type="java.lang.AssertionError" message="Status code is not 422 expected [422] but found [200]">
      <![CDATA[java.lang.AssertionError: Status code is not 422 expected [422] but found [200]
at com.nagarro.util.CommonUtility.Verify_ResponseCode422(CommonUtility.java:211)
at com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture.testcases_Verify__CancelTheOrderAfterCancel(TestcasesForOrderPlacedInPresentNFuture.java:323)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testcases_Verify__CancelTheOrderAfterCancel -->
  <testcase name="testcases_Verify__CompleteTheOrderAfterCancel" time="6.331" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__TakeTheOrderAfterCancelled" time="6.016" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="testcases_Verify__FetchTheOrderDetailsNotCreated" time="0.656" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
</testsuite> <!-- place order at 3 stops in present and future -->
